version: "3"
services:
  hmpps-welcome-people-into-prison-api:
    build:
      context: .
    network_mode: "host"
    container_name: hmpps-welcome-people-into-prison-api
    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ping"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev
      - OAUTH_ENDPOINT_URL=http://hmpps-auth:8080/auth
      - PRISON_ENDPOINT_URL=http://prison-api:8080

  hmpps-welcome-people-into-prison-api-db:
    image: postgres
    networks:
      - hmpps
    container_name: hmpps-welcome-people-into-prison-api-db
    restart: always
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=hmpps-welcome-people-into-prison-api-db

  prison-api:
    image: quay.io/hmpps/prison-api:latest
    networks:
      - hmpps
    container_name: prison-api
    depends_on:
      - hmpps-auth
    ports:
      - "8082:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
    environment:
      - SPRING_PROFILES_ACTIVE=nomis-hsqldb

  hmpps-auth:
    image: quay.io/hmpps/hmpps-auth:latest
    networks:
      - hmpps
    container_name: hmpps-auth
    ports:
      - "8083:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auth/health"]
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DELIUS_ENABLED=false

networks:
  hmpps:
