version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@10

parameters:
  alerts-slack-channel:
    type: string
    default: move-a-prisoner-alerts
  releases-slack-channel:
    type: string
    default: dps-releases

jobs:
  validate:
    executor:
      name: hmpps/java
      tag: "21.0"
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle.kts" }}
            - gradle-
      - run:
          command: ./gradlew -Dorg.gradle.jvmargs="--illegal-access=permit" -Dkotlin.daemon.jvm.options="--illegal-access=permit" check koverHtmlReport
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }}
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports/tests
          destination: test-report
      - store_artifacts:
          path: build/reports/kover/html
          destination: test-coverage-report

workflows:
  version: 2
