---
# Per environment values which override defaults in hmpps-welcome-people-into-prison-api/values.yaml

generic-service:
  replicaCount: 4

  ingress:
    host: welcome-api-preprod.prison.service.justice.gov.uk
  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    OAUTH_ENDPOINT_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    BASM_ENDPOINT_URL: "https://hmpps-book-secure-move-api-preprod.apps.live-1.cloud-platform.service.justice.gov.uk"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
