---
# Per environment values which override defaults in hmpps-welcome-people-into-prison-api/values.yaml

generic-service:
  replicaCount: 4

  ingress:
    hosts:
      - welcome-api.prison.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    OAUTH_ENDPOINT_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    PRISON_ENDPOINT_URL: "https://prison-api.prison.service.justice.gov.uk"
    BASM_ENDPOINT_URL: "https://api.bookasecuremove.service.justice.gov.uk"
    PRISONER_SEARCH_ENDPOINT_URL: "https://prisoner-search.prison.service.justice.gov.uk"
    PRISON_REGISTER_ENDPOINT_URL: "https://prison-register.hmpps.service.justice.gov.uk"
    MANAGE_USERS_ENDPOINT_URL: "https://manage-users-api.hmpps.service.justice.gov.uk"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: move-a-prisoner-alerts-prod
