---
# Per environment values which override defaults in hmpps-welcome-people-into-prison-api/values.yaml

generic-service:
  replicaCount: 4

  ingress:
    host: welcome-api-preprod.prison.service.justice.gov.uk
  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json

# CloudPlatform AlertManager receiver to route promethues alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
