---
# Per environment values which override defaults in hmpps-welcome-people-into-prison-api/values.yaml

generic-service:
  replicaCount: 4

  ingress:
    host: welcome-api.prison.service.justice.gov.uk
    annotations:
      external-dns.alpha.kubernetes.io/set-identifier: hmpps-welcome-people-into-prison-api-hmpps-welcome-to-prison-prod-blue
  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    OAUTH_ENDPOINT_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    PRISON_ENDPOINT_URL: "https://api.prison.service.justice.gov.uk"
    BASM_ENDPOINT_URL: "https://api.bookasecuremove.service.justice.gov.uk"
    PRISONER_SEARCH_ENDPOINT_URL: "https://prisoner-offender-search.prison.service.justice.gov.uk"
    PRISON_REGISTER_ENDPOINT_URL: "https://prison-register.hmpps.service.justice.gov.uk"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: digital-prison-service
